---
abstract: 'easy and powerful image manipulation for Mojolicious'
author:
  - 'alexbyk <alexbyk@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Images
requires:
  IO::All: '0'
  Imager: '0'
  Mojolicious: '5.28'
  perl: v5.20.0
resources:
  bugtracker: http://github.com/alexbyk/mojo-images/issues
  repository: http://github.com/alexbyk/mojo-images
version: '0.003'
